defmodule PhoenixKitProjects.CalendarDisplay do
  @moduledoc """
  Maps projects to `PhoenixLiveSchedule.Event` structs for the Overview
  dashboard calendar.

  Each project becomes an all-day, multi-day "ongoing line" on a month grid:
  running projects span start → planned-end (reaching at least today, so they
  read as ongoing), completed projects span start → completion, and scheduled
  projects get a one-day marker on their planned start.

  Bars are colored by **project identity** — a stable color per project, picked
  by hashing the project id over a fixed palette of hues spread around the color
  wheel — so adjacent and stacked bars stay tellable apart. Lifecycle status is
  conveyed by the dashboard's project cards, with one exception: for a running
  summary the caller tags `late: true`, only the stretch of the bar PAST its
  planned end (planned_end+1 .. today) is highlighted — via `extra.highlight`
  with the `pk-overdue` class (it renders that stretch in the INVERSE of the
  bar's own color, animated per `animation_style/0` — wave/flash/off, configured
  on `/admin/settings/projects`) — so the length of the tail shows how late the
  project is. The rest keeps its identity color.

  `end` is exclusive in PhoenixLiveSchedule (`[start, end)`), so the inclusive
  last day gets `+1`. Projects without a placeable start date are dropped.
  """

  alias PhoenixKitProjects.Schemas.Project
  alias PhoenixLiveSchedule.Event

  # Distinct {bg, text} pairs — fixed Tailwind hues spread around the color wheel
  # (≥28° apart), NOT daisyUI semantic colors (those clustered into several
  # near-identical pinks/reds + two blues in this theme). Each project is pinned
  # to one by hashing its id. Listed as literals so the host's Tailwind (scanning
  # this module via `css_sources/0`) emits them. (The overdue stretch shows the
  # INVERSE of each color via CSS `filter: invert`, so no color table is needed.)
  @palette [
    {"bg-blue-600", "text-white"},
    {"bg-cyan-500", "text-neutral-900"},
    {"bg-emerald-600", "text-white"},
    {"bg-lime-500", "text-neutral-900"},
    {"bg-amber-400", "text-neutral-900"},
    {"bg-orange-600", "text-white"},
    {"bg-fuchsia-600", "text-white"},
    {"bg-violet-600", "text-white"}
  ]

  # Class applied (via `extra.highlight`) to the OVERDUE day-segments of a late
  # project's bar — the stretch from its planned end to today. Its animation is
  # generated by `animation_style/0` from the settings below.
  @overdue_class "pk-overdue"

  # ── Overdue animation (configured on /admin/settings/projects) ──────────────
  # The overdue stretch always renders in the INVERSE of the bar's own color
  # (`filter: invert`); these settings pick HOW it animates and generate the
  # `<style>` the Overview injects. Validated on read/write (mode against the
  # allowed set, numbers clamped) so a malformed install resolves to safe
  # defaults matching what shipped before this was configurable.
  @module "projects"

  @anim_mode_key "projects_cal_overdue_mode"
  @anim_speed_key "projects_cal_overdue_speed"
  @anim_bright_min_key "projects_cal_overdue_bright_min"
  @anim_bright_max_key "projects_cal_overdue_bright_max"
  @anim_wave_step_key "projects_cal_overdue_wave_step"

  # wave = a single band sweeps across all overdue days (date-synced); flash =
  # every overdue day pulses together; off = static inverse color, no motion.
  @anim_modes ~w(wave flash off)

  @default_mode "wave"
  @default_speed 7.0
  @default_bright_min 0.78
  @default_bright_max 1.18
  @default_wave_step 0.16

  # {lo, hi} clamp ranges for each numeric setting (also bound the form inputs).
  @speed_range {1.0, 20.0}
  @bright_min_range {0.2, 1.0}
  @bright_max_range {1.0, 2.5}
  @wave_step_range {0.02, 1.0}

  @doc """
  Builds the calendar event list from the dashboard's already-loaded data.

    * `active_summaries` — `Projects.project_tree_summary/1` maps for running
      projects (carry `:project`, `:planned_end`, `:progress_pct`), each tagged
      by the caller with `:late` (boolean) to drive the blink
    * `completed` / `upcoming` — `[Project.t()]` (recently completed / scheduled)
    * `lang` — content language for project titles
    * `today` — anchor so a running project's bar always reaches at least today
    * `offset` — viewer timezone offset (e.g. "+3"); UTC datetimes are converted
      to local calendar dates with it, so bars land on the same day the viewer sees
  """
  @spec events([map()], [Project.t()], [Project.t()], String.t() | nil, Date.t(), String.t()) ::
          [Event.t()]
  def events(
        active_summaries,
        completed,
        upcoming,
        lang,
        today \\ Date.utc_today(),
        offset \\ "0"
      ) do
    running = Enum.map(active_summaries, &running_event(&1, lang, today, offset))
    done = Enum.map(completed, &completed_event(&1, lang, offset))
    scheduled = Enum.map(upcoming, &scheduled_event(&1, lang, offset))

    Enum.reject(running ++ done ++ scheduled, &is_nil/1)
  end

  defp running_event(
         %{project: %Project{started_at: %DateTime{} = started} = project} = summary,
         lang,
         today,
         offset
       ) do
    start_d = to_date(started, offset)
    planned_end_d = to_date(summary[:planned_end], offset)
    # An in-progress project should always read as ongoing, so its bar reaches
    # at least today; a later planned end extends it further. When it's late, the
    # stretch past planned_end is highlighted so the red length shows how late.
    last_day = latest([start_d, today, planned_end_d])
    late? = summary[:late]

    # Late projects get slot_priority 0 so the lib packs them into the top slots
    # — grouping them (and their overdue waves) together; everything else is 1.
    extra =
      late?
      |> overdue_highlight(planned_end_d, today)
      |> Map.put(:slot_priority, if(late?, do: 0, else: 1))

    event(project, start_d, last_day, summary[:progress_pct], lang, extra)
  end

  defp running_event(_, _, _, _), do: nil

  # Highlight only the overdue stretch (planned_end+1 .. today) of a late
  # project. Requires a planned end in the past; without one there's no
  # measurable overdue extent, so nothing is highlighted (the card still flags it).
  defp overdue_highlight(true, %Date{} = planned_end_d, today) do
    if Date.compare(planned_end_d, today) == :lt do
      # `to` (exclusive) = today+1 explicitly bounds the overdue stretch. (The
      # wave is keyed to absolute date, not length, so all projects stay in sync.)
      %{
        highlight: %{
          from: Date.add(planned_end_d, 1),
          to: Date.add(today, 1),
          class: @overdue_class
        }
      }
    else
      %{}
    end
  end

  defp overdue_highlight(_late, _planned_end_d, _today), do: %{}

  defp completed_event(
         %Project{started_at: %DateTime{} = started, completed_at: %DateTime{} = done} = project,
         lang,
         offset
       ) do
    start_d = to_date(started, offset)

    event(project, start_d, latest([start_d, to_date(done, offset)]), 100, lang, %{
      slot_priority: 1
    })
  end

  # Completed without a recorded start → a one-day marker on the completion day.
  defp completed_event(%Project{completed_at: %DateTime{} = done} = project, lang, offset) do
    d = to_date(done, offset)
    event(project, d, d, 100, lang, %{slot_priority: 1})
  end

  defp completed_event(_, _, _), do: nil

  defp scheduled_event(%Project{scheduled_start_date: %DateTime{} = at} = project, lang, offset) do
    d = to_date(at, offset)
    event(project, d, d, nil, lang, %{slot_priority: 1})
  end

  defp scheduled_event(_, _, _), do: nil

  defp event(%Project{} = project, start_d, last_day_inclusive, pct, lang, extra) do
    {bg, text} = color_for(project.uuid)

    PhoenixLiveSchedule.event(project.uuid, start_d,
      title: Project.localized_name(project, lang),
      end: Date.add(last_day_inclusive, 1),
      all_day: true,
      color: bg,
      text_color: text,
      extra: Map.put(extra, :progress_pct, pct)
    )
  end

  # Deterministic palette pick from the project id.
  @spec color_for(term()) :: {String.t(), String.t()}
  def color_for(uuid), do: Enum.at(@palette, rem(:erlang.phash2(uuid), length(@palette)))

  # A UTC datetime as a calendar Date in the viewer's timezone (offset like
  # "+3"), so bar placement shares the same local basis as the `today` anchor.
  defp to_date(%DateTime{} = dt, offset),
    do: dt |> PhoenixKit.Utils.Date.shift_to_offset(offset) |> DateTime.to_date()

  defp to_date(%Date{} = d, _offset), do: d
  defp to_date(_, _offset), do: nil

  defp latest(dates) do
    dates
    |> Enum.reject(&is_nil/1)
    |> Enum.max(Date)
  end

  # ── Overdue animation settings + CSS generation ─────────────────────────────

  @doc "Allowed overdue-animation modes (for the settings form)."
  @spec anim_modes() :: [String.t()]
  def anim_modes, do: @anim_modes

  @doc "Clamp range {lo, hi} for a numeric overdue field (bounds the form input)."
  @spec anim_range(String.t()) :: {float(), float()}
  def anim_range("speed"), do: @speed_range
  def anim_range("brightness_min"), do: @bright_min_range
  def anim_range("brightness_max"), do: @bright_max_range
  def anim_range("wave_step"), do: @wave_step_range

  @doc "Current overdue-animation settings (validated, with safe defaults)."
  @spec read_animation() :: %{
          mode: String.t(),
          speed: float(),
          brightness_min: float(),
          brightness_max: float(),
          wave_step: float()
        }
  def read_animation do
    %{
      mode: anim_enum(@anim_mode_key, @default_mode),
      speed: anim_float(@anim_speed_key, @default_speed, @speed_range),
      brightness_min: anim_float(@anim_bright_min_key, @default_bright_min, @bright_min_range),
      brightness_max: anim_float(@anim_bright_max_key, @default_bright_max, @bright_max_range),
      wave_step: anim_float(@anim_wave_step_key, @default_wave_step, @wave_step_range)
    }
  end

  @doc """
  Persist one overdue-animation field (`"mode"`, `"speed"`, `"brightness_min"`,
  `"brightness_max"`, `"wave_step"`). An invalid field or value is ignored.
  """
  @spec put_animation(String.t(), term()) :: term()
  def put_animation("mode", v) do
    if v in @anim_modes,
      do: PhoenixKit.Settings.update_setting_with_module(@anim_mode_key, v, @module),
      else: :ignore
  end

  def put_animation("speed", v), do: put_anim_float(@anim_speed_key, v, @speed_range)

  def put_animation("brightness_min", v),
    do: put_anim_float(@anim_bright_min_key, v, @bright_min_range)

  def put_animation("brightness_max", v),
    do: put_anim_float(@anim_bright_max_key, v, @bright_max_range)

  def put_animation("wave_step", v), do: put_anim_float(@anim_wave_step_key, v, @wave_step_range)
  def put_animation(_field, _value), do: :ignore

  @doc "Restore every overdue-animation setting to its default."
  @spec reset_animation() :: :ok
  def reset_animation do
    PhoenixKit.Settings.update_setting_with_module(@anim_mode_key, @default_mode, @module)
    put_anim_float(@anim_speed_key, @default_speed, @speed_range)
    put_anim_float(@anim_bright_min_key, @default_bright_min, @bright_min_range)
    put_anim_float(@anim_bright_max_key, @default_bright_max, @bright_max_range)
    put_anim_float(@anim_wave_step_key, @default_wave_step, @wave_step_range)
    :ok
  end

  @doc """
  The `<style>` block for the overdue animation, generated from the current
  settings. Safe to inject with `Phoenix.HTML.raw/1`: every interpolated value
  is a validated enum or clamped number, never free text.
  """
  @spec animation_style() :: String.t()
  def animation_style, do: animation_style(read_animation())

  @doc "As `animation_style/0`, for an already-read config map (avoids a re-read)."
  @spec animation_style(map()) :: String.t()
  def animation_style(cfg), do: "<style>\n" <> animation_css(cfg) <> "\n</style>"

  @doc """
  CSS body (no surrounding `<style>` tag) for an overdue-animation config map of
  the shape `read_animation/0` returns. Public so tests and a settings preview
  can render a given config without touching the settings store.
  """
  @spec animation_css(map()) :: String.t()
  # off → static inverse color, no motion (a mid brightness so it reads clearly
  # as the inverse without glaring).
  def animation_css(%{mode: "off"} = cfg) do
    ".pk-overdue { filter: invert(1) brightness(#{num((cfg.brightness_min + cfg.brightness_max) / 2)}); }"
  end

  # wave → each overdue day is phase-shifted by its absolute date (--pk-hl-day),
  # so one band travels across every project in sync. flash → same keyframe with
  # no delay, so all overdue days pulse together. Both use the inverse-color
  # brightness pulse; reduced-motion falls back to a static inverse.
  def animation_css(cfg) do
    delay =
      if cfg.mode == "wave",
        do: "\n      animation-delay: calc(var(--pk-hl-day, 0) * -#{num(cfg.wave_step)}s);",
        else: ""

    """
    @keyframes pk-overdue-wave {
          0%, 42%, 100% { filter: invert(1) brightness(#{num(cfg.brightness_min)}); }
          50% { filter: invert(1) brightness(#{num(cfg.brightness_max)}); }
          58% { filter: invert(1) brightness(#{num(cfg.brightness_min)}); }
        }
        .pk-overdue {
          filter: invert(1) brightness(#{num(cfg.brightness_min)});
          animation: pk-overdue-wave #{num(cfg.speed)}s ease-in-out infinite;#{delay}
        }
        @media (prefers-reduced-motion: reduce) {
          .pk-overdue { animation: none; filter: invert(1); }
        }\
    """
  end

  defp anim_enum(key, default) do
    value = PhoenixKit.Settings.get_setting(key, default)
    if value in @anim_modes, do: value, else: default
  end

  defp anim_float(key, default, range) do
    case Float.parse(PhoenixKit.Settings.get_setting(key, to_string(default))) do
      {f, _} -> clamp(f, range)
      :error -> default
    end
  end

  defp put_anim_float(key, value, range) do
    case Float.parse(to_string(value)) do
      {f, _} ->
        PhoenixKit.Settings.update_setting_with_module(key, to_string(clamp(f, range)), @module)

      :error ->
        :ignore
    end
  end

  defp clamp(f, {lo, hi}), do: f |> max(lo) |> min(hi)

  # Trim a float for CSS output: integers lose the trailing ".0" (7.0 -> "7").
  defp num(f) when is_float(f) do
    if f == Float.round(f), do: Integer.to_string(trunc(f)), else: Float.to_string(f)
  end
end
