defmodule PhoenixKitProjects.CalendarDisplay do
  @moduledoc """
  Maps projects — and, for the default Tasks mode, their scheduled tasks — to
  `PhoenixLiveCalendar.Event` structs for the Overview dashboard calendar.

  Two mapping modes back the Overview calendar's mode toggle:

    * `task_events/3` (the **Tasks** default) — every leaf task across every
      given project, placed on the days its `ScheduleLayout` span covers,
      colored by the OWNING project's identity color so a day reads as "what
      happens today, across projects". Same-day tasks stack as chips,
      multi-day tasks as bars; the LiveView caps the per-day count and the
      grid shows a Google-style "+N more" for the rest.
    * `events/6` (the **Projects** mode — the original view) — each project
      as one all-day "ongoing line": running projects span start →
      planned-end (reaching at least today, so they read as ongoing),
      completed projects span start → completion, and scheduled projects get
      a one-day marker on their planned start.

  Bars are colored by **project identity** — a stable color per project, picked
  by hashing the project id over a fixed palette of hues spread around the color
  wheel — so adjacent and stacked bars stay tellable apart. Lifecycle status is
  conveyed by the dashboard's project cards, with one exception: for a running
  summary the caller tags `late: true`, only the stretch of the bar PAST its
  planned end (planned_end+1 .. today) is highlighted — via `extra.highlight`
  with the `pk-overdue` class (it marks that stretch in the INVERSE of the bar's
  own colour — diagonal stripes over the identity colour, or a solid fill —
  animated per `animation_style/0`, all configured on `/admin/settings/projects`)
  — so the length of the marked tail shows how late the project is. The rest
  keeps its identity color.

  `end` is exclusive in PhoenixLiveCalendar (`[start, end)`), so the inclusive
  last day gets `+1`. Projects without a placeable start date are dropped.
  """

  use Gettext, backend: PhoenixKitProjects.Gettext

  alias PhoenixKitProjects.Schemas.{Assignment, Project}
  alias PhoenixLiveCalendar.Event

  # Distinct {bg, text} pairs — fixed Tailwind hues spread around the color wheel
  # (≥28° apart), NOT daisyUI semantic colors (those clustered into several
  # near-identical pinks/reds + two blues in this theme). Each project is pinned
  # to one by hashing its id. Listed as literals so the host's Tailwind (scanning
  # this module via `css_sources/0`) emits them. (The overdue stretch shows the
  # INVERSE of each color via CSS `filter: invert`, so no color table is needed.)
  @palette [
    {"bg-blue-600", "text-white"},
    {"bg-cyan-500", "text-neutral-900"},
    {"bg-emerald-600", "text-white"},
    {"bg-lime-500", "text-neutral-900"},
    {"bg-amber-400", "text-neutral-900"},
    {"bg-orange-600", "text-white"},
    {"bg-fuchsia-600", "text-white"},
    {"bg-violet-600", "text-white"}
  ]

  # Class applied (via `extra.highlight`) to the OVERDUE day-segments of a late
  # project's bar — the stretch from its planned end to today. Its look (inverse-
  # colour stripes or solid fill) + animation is generated by `animation_style/0`
  # from the settings below.
  @overdue_class "pk-overdue"

  # Tasks-mode late marker: a red inset ring on the chip/bar (Tailwind
  # utilities as literals so the host's scan emits them; the identity color
  # stays readable underneath).
  @late_class "ring-2 ring-error ring-inset"

  # ── Overdue animation (configured on /admin/settings/projects) ──────────────
  # The overdue stretch is marked in the INVERSE of the bar's own color — either
  # as diagonal stripes (default) or a solid fill (`pattern`). These settings
  # pick the pattern + HOW it animates and generate the `<style>` the Overview
  # injects. Validated on read/write (enums against the allowed set, numbers
  # clamped) so a malformed install resolves to safe defaults.
  @module "projects"

  @anim_pattern_key "projects_cal_overdue_pattern"
  @anim_mode_key "projects_cal_overdue_mode"
  @anim_speed_key "projects_cal_overdue_speed"
  @anim_bright_min_key "projects_cal_overdue_bright_min"
  @anim_bright_max_key "projects_cal_overdue_bright_max"
  @anim_wave_step_key "projects_cal_overdue_wave_step"
  @anim_opacity_key "projects_cal_overdue_opacity"
  @late_marker_key "projects_cal_late_marker"

  # stripes = diagonal inverse-colour hazard stripes over the identity colour
  # (keeps the project's colour readable); solid = the whole overdue stretch
  # flips to the inverse colour.
  @anim_patterns ~w(stripes solid)

  # wave = motion travels (stripes slide horizontally across the bar / a band
  # sweeps); flash = pulses in place; off = static, no motion.
  @anim_modes ~w(wave flash off)

  # How a late TASK (chip/bar on the Tasks-mode Overview + the project
  # Calendar tab) is marked: ring = the red inset ring; pattern = the same
  # configured overdue pattern the Projects-mode bars use, so the two "late"
  # visuals can match.
  @late_markers ~w(ring pattern)

  @default_pattern "stripes"
  # Static by default — the stripes already read as "overdue" without motion;
  # wave/flash are opt-in.
  @default_mode "off"
  @default_speed 7.0
  @default_bright_min 0.78
  @default_bright_max 1.18
  @default_wave_step 0.16
  @default_opacity 1.0
  @default_late_marker "ring"

  # {lo, hi} clamp ranges for each numeric setting (also bound the form inputs).
  @speed_range {1.0, 20.0}
  @bright_min_range {0.2, 1.0}
  @bright_max_range {1.0, 2.5}
  @wave_step_range {0.02, 1.0}
  @opacity_range {0.05, 1.0}

  @doc """
  Builds the calendar event list from the dashboard's already-loaded data.

    * `active_summaries` — `Projects.project_tree_summary/1` maps for running
      projects (carry `:project` and `:planned_end`), each tagged by the
      caller with `:late` (boolean) to drive the blink
    * `completed` / `upcoming` — `[Project.t()]` (recently completed / scheduled)
    * `lang` — content language for project titles
    * `today` — anchor so a running project's bar always reaches at least today
    * `offset` — viewer timezone offset (e.g. "+3"); UTC datetimes are converted
      to local calendar dates with it, so bars land on the same day the viewer sees
  """
  @spec events([map()], [Project.t()], [Project.t()], String.t() | nil, Date.t(), String.t()) ::
          [Event.t()]
  def events(
        active_summaries,
        completed,
        upcoming,
        lang,
        today \\ Date.utc_today(),
        offset \\ "0"
      ) do
    running = Enum.map(active_summaries, &running_event(&1, lang, today, offset))
    done = Enum.map(completed, &completed_event(&1, lang, offset))
    scheduled = Enum.map(upcoming, &scheduled_event(&1, lang, offset))

    Enum.reject(running ++ done ++ scheduled, &is_nil/1)
  end

  @doc """
  Builds the Tasks-mode event list (+ a per-task metadata map) from prepared
  `{item, span}` pairs — each a `PhoenixKitProjects.ScheduleLayout` item with
  its computed `%{start: NaiveDateTime, end: NaiveDateTime}` span. Pure: the
  caller runs the schedule walk (`ScheduleLayout.tree/1` per project) and
  passes only the LEAF items (sub-project container assignments excluded —
  their child tasks stand for themselves here).

  Each task becomes an all-day event spanning its scheduled days in the
  viewer's timezone (`offset`, e.g. `"+3"` — same local basis as the rest of
  the Overview), colored by the OWNING project's identity color
  (`color_for/1`), so tasks group visually by project across the month.
  Exclusive ends (`[start, end)`): a span ending exactly at local midnight
  doesn't occupy that day, and a zero-length span still shows as a one-day
  chip.

  Returns `{events, meta}` — `meta` keyed by assignment uuid with
  `:project_uuid` / `:project_name` / `:status` / `:late` for the day popup's
  rows, the overdue filter, and click navigation.

  Options:

    * `:now` — a UTC `NaiveDateTime`; when given, a not-done task whose span
      ended before it is **late**: its chip/bar gets the late marker class
      and its meta entry `late: true`. Without `:now` nothing is flagged
      (pure date math only).
    * `:late_class` — the marker class for late chips/bars (defaults to the
      red inset ring; pass `late_marker_class(read_animation())` to honor
      the configured marker).
  """
  @spec task_events(
          [{map(), %{start: NaiveDateTime.t(), end: NaiveDateTime.t()}}],
          String.t() | nil,
          String.t(),
          keyword()
        ) ::
          {[Event.t()], %{optional(String.t()) => map()}}
  def task_events(items_with_spans, lang, offset \\ "0", opts \\ []) do
    now = Keyword.get(opts, :now)
    late_class = Keyword.get(opts, :late_class, @late_class)

    Enum.map_reduce(items_with_spans, %{}, fn {item, span}, meta ->
      %{assignment: a, project: project} = item

      start_d = to_date(naive_to_utc(span.start), offset)
      end_d = exclusive_end_date(start_d, span.end, offset)
      {bg, text} = color_for(project.uuid)
      late? = task_late?(a, span, now)

      event =
        PhoenixLiveCalendar.event(a.uuid, start_d,
          title: Assignment.label(a, lang) || gettext("(untitled task)"),
          end: end_d,
          all_day: true,
          color: bg,
          text_color: text,
          class: if(late?, do: late_class)
        )

      entry = %{
        project_uuid: project.uuid,
        project_name: Project.localized_name(project, lang),
        status: a.status,
        late: late?
      }

      {event, Map.put(meta, a.uuid, entry)}
    end)
  end

  @doc """
  Per-day caps for the month grids, shared by BOTH calendars — the "+N more"
  link / whole-day popup contract depends on the two grids agreeing on when
  a day overflows. `max_events/0` caps single-day chips, `max_multiday/0`
  caps multi-day bar slots.
  """
  @spec max_events() :: pos_integer()
  def max_events, do: 3

  @spec max_multiday() :: pos_integer()
  def max_multiday, do: 4

  @doc """
  Events whose `[start, end)` span covers `date`, soonest-starting first —
  the shared day-popup row source for both calendars.
  """
  @spec events_on([Event.t()], Date.t()) :: [Event.t()]
  def events_on(events, date) do
    events
    |> Enum.filter(fn e ->
      Date.compare(e.start, date) != :gt and Date.compare(date, Date.add(e.end, -1)) != :gt
    end)
    |> Enum.sort_by(&{&1.start, &1.title})
  end

  @doc """
  A task is late when it isn't done and its scheduled span ended before
  `now` — the schedule says it should already have finished. The shared rule
  behind both calendars' red rings, `late` badges, and Overdue-only filters
  (a `nil` `now` flags nothing — pure date math only).
  """
  @spec task_late?(
          map(),
          %{:end => NaiveDateTime.t(), optional(atom()) => term()},
          NaiveDateTime.t() | nil
        ) ::
          boolean()
  def task_late?(_a, _span, nil), do: false

  def task_late?(a, span, %NaiveDateTime{} = now) do
    a.status != "done" and NaiveDateTime.compare(span.end, now) == :lt
  end

  @doc """
  The exclusive end DATE for a span ending at `e` (UTC naive). With a viewer
  `offset` (`"+3"`) the end is evaluated in the local frame; `nil` keeps UTC —
  the project Calendar tab's Timeline-parity frame. An end falling exactly on
  (local) midnight doesn't occupy that day, any later instant does. Floored
  one day past the start so a zero-length span still shows as a one-day chip.
  """
  @spec exclusive_end_date(Date.t(), NaiveDateTime.t(), String.t() | nil) :: Date.t()
  def exclusive_end_date(start_d, e, offset \\ nil)

  def exclusive_end_date(start_d, %NaiveDateTime{} = e, nil) do
    e_date = NaiveDateTime.to_date(e)

    exclusive =
      if NaiveDateTime.compare(e, NaiveDateTime.new!(e_date, ~T[00:00:00])) == :eq,
        do: e_date,
        else: Date.add(e_date, 1)

    Enum.max([exclusive, Date.add(start_d, 1)], Date)
  end

  def exclusive_end_date(start_d, %NaiveDateTime{} = e, offset) do
    local_end = PhoenixKit.Utils.Date.shift_to_offset(naive_to_utc(e), offset)
    e_date = DateTime.to_date(local_end)

    exclusive =
      if local_end.hour == 0 and local_end.minute == 0 and local_end.second == 0,
        do: e_date,
        else: Date.add(e_date, 1)

    Enum.max([exclusive, Date.add(start_d, 1)], Date)
  end

  defp naive_to_utc(%NaiveDateTime{} = ndt), do: DateTime.from_naive!(ndt, "Etc/UTC")

  defp running_event(
         %{project: %Project{started_at: %DateTime{} = started} = project} = summary,
         lang,
         today,
         offset
       ) do
    start_d = to_date(started, offset)
    planned_end_d = to_date(summary[:planned_end], offset)
    # An in-progress project should always read as ongoing, so its bar reaches
    # at least today; a later planned end extends it further. When it's late, the
    # stretch past planned_end is highlighted so the red length shows how late.
    last_day = latest([start_d, today, planned_end_d])
    late? = summary[:late]

    # Late projects get slot_priority 0 so the lib packs them into the top slots
    # — grouping them (and their overdue waves) together; everything else is 1.
    extra =
      late?
      |> overdue_highlight(planned_end_d, today)
      |> Map.put(:slot_priority, if(late?, do: 0, else: 1))

    event(project, start_d, last_day, lang, extra)
  end

  defp running_event(_, _, _, _), do: nil

  # Highlight only the overdue stretch (planned_end+1 .. today) of a late
  # project. Requires a planned end in the past; without one there's no
  # measurable overdue extent, so nothing is highlighted (the card still flags it).
  defp overdue_highlight(true, %Date{} = planned_end_d, today) do
    if Date.compare(planned_end_d, today) == :lt do
      # `to` (exclusive) = today+1 explicitly bounds the overdue stretch. (The
      # wave is keyed to absolute date, not length, so all projects stay in sync.)
      %{
        highlight: %{
          from: Date.add(planned_end_d, 1),
          to: Date.add(today, 1),
          class: @overdue_class
        }
      }
    else
      %{}
    end
  end

  defp overdue_highlight(_late, _planned_end_d, _today), do: %{}

  defp completed_event(
         %Project{started_at: %DateTime{} = started, completed_at: %DateTime{} = done} = project,
         lang,
         offset
       ) do
    start_d = to_date(started, offset)

    event(project, start_d, latest([start_d, to_date(done, offset)]), lang, %{slot_priority: 1})
  end

  # Completed without a recorded start → a one-day marker on the completion day.
  defp completed_event(%Project{completed_at: %DateTime{} = done} = project, lang, offset) do
    d = to_date(done, offset)
    event(project, d, d, lang, %{slot_priority: 1})
  end

  defp completed_event(_, _, _), do: nil

  defp scheduled_event(%Project{scheduled_start_date: %DateTime{} = at} = project, lang, offset) do
    d = to_date(at, offset)
    event(project, d, d, lang, %{slot_priority: 1})
  end

  defp scheduled_event(_, _, _), do: nil

  defp event(%Project{} = project, start_d, last_day_inclusive, lang, extra) do
    {bg, text} = color_for(project.uuid)

    PhoenixLiveCalendar.event(project.uuid, start_d,
      title: Project.localized_name(project, lang),
      end: Date.add(last_day_inclusive, 1),
      all_day: true,
      color: bg,
      text_color: text,
      extra: extra
    )
  end

  # Deterministic palette pick from the project id.
  @spec color_for(term()) :: {String.t(), String.t()}
  def color_for(uuid), do: Enum.at(@palette, rem(:erlang.phash2(uuid), length(@palette)))

  # A UTC datetime as a calendar Date in the viewer's timezone (offset like
  # "+3"), so bar placement shares the same local basis as the `today` anchor.
  defp to_date(%DateTime{} = dt, offset),
    do: dt |> PhoenixKit.Utils.Date.shift_to_offset(offset) |> DateTime.to_date()

  defp to_date(%Date{} = d, _offset), do: d
  defp to_date(_, _offset), do: nil

  defp latest(dates) do
    dates
    |> Enum.reject(&is_nil/1)
    |> Enum.max(Date)
  end

  # ── Overdue animation settings + CSS generation ─────────────────────────────

  @doc """
  Tailwind classes giving any of OUR clickable controls in-flight feedback:
  LiveView tags the clicked element with `phx-click-loading` for the round
  trip; these arbitrary variants pulse + dim it and block double-clicks.
  Returned from a function (not inlined per call site) so every control
  shares one literal for the Tailwind scan.
  """
  @spec loading_class() :: String.t()
  def loading_class do
    "[&.phx-click-loading]:opacity-60 [&.phx-click-loading]:animate-pulse " <>
      "[&.phx-click-loading]:pointer-events-none"
  end

  @doc """
  Tasks-mode late marker: a red inset ring on the chip/bar. Returned from a
  function (not duplicated as a literal per call site) so the Overview
  calendar and the project Calendar tab can't drift apart.
  """
  @spec late_class() :: String.t()
  def late_class, do: @late_class

  @doc """
  The late-task marker class for a `read_animation/0` config: `"ring"` (the
  default red inset ring) or `"pattern"` — the `pk-overdue` overlay, i.e. the
  same configured stripes/solid look the Projects-mode overdue stretch uses,
  so the two "late" visuals can match. Consumers using `"pattern"` must also
  inject `animation_style/1` (and ideally wrap the grid in `SyncAnimations`).
  """
  @spec late_marker_class(map()) :: String.t()
  def late_marker_class(%{late_marker: "pattern"}), do: @overdue_class
  def late_marker_class(_cfg), do: @late_class

  @doc """
  A `<style>` block giving the calendar LIBRARY's clickable nodes (event
  chips, multi-day bars, day cells, "+N more") the same in-flight pulse —
  their classes are lib-rendered, so the Tailwind-variant approach above
  can't reach them. Static CSS, safe for `Phoenix.HTML.raw/1`.
  """
  @spec loading_style() :: String.t()
  def loading_style do
    """
    <style>
    .cal-event.phx-click-loading, .cal-multiday-bar.phx-click-loading,
    .cal-day-cell.phx-click-loading, .cal-more-link.phx-click-loading {
      opacity: 0.5;
      animation: pk-cal-click-pulse 1s ease-in-out infinite;
    }
    @keyframes pk-cal-click-pulse { 50% { opacity: 0.25; } }
    @media (prefers-reduced-motion: reduce) {
      .cal-event.phx-click-loading, .cal-multiday-bar.phx-click-loading,
      .cal-day-cell.phx-click-loading, .cal-more-link.phx-click-loading {
        animation: none;
      }
    }
    </style>
    """
  end

  @doc "Allowed overdue-animation modes (for the settings form)."
  @spec anim_modes() :: [String.t()]
  def anim_modes, do: @anim_modes

  @doc "Allowed overdue-marker patterns (for the settings form)."
  @spec anim_patterns() :: [String.t()]
  def anim_patterns, do: @anim_patterns

  @doc "Allowed late-task marker styles (for the settings form)."
  @spec late_markers() :: [String.t()]
  def late_markers, do: @late_markers

  @doc "Clamp range {lo, hi} for a numeric overdue field (bounds the form input)."
  @spec anim_range(String.t()) :: {float(), float()}
  def anim_range("speed"), do: @speed_range
  def anim_range("brightness_min"), do: @bright_min_range
  def anim_range("brightness_max"), do: @bright_max_range
  def anim_range("wave_step"), do: @wave_step_range
  def anim_range("opacity"), do: @opacity_range

  @doc "Current overdue-animation settings (validated, with safe defaults)."
  @spec read_animation() :: %{
          pattern: String.t(),
          mode: String.t(),
          speed: float(),
          brightness_min: float(),
          brightness_max: float(),
          wave_step: float(),
          opacity: float(),
          late_marker: String.t()
        }
  def read_animation do
    # One batched, uncached query for all keys instead of a SELECT per key —
    # this runs on every Overview reload (each `{:projects, …}` broadcast), not
    # just mount. Direct reads keep the settings page's live demo fresh.
    values =
      PhoenixKit.Settings.get_settings_direct([
        @anim_pattern_key,
        @anim_mode_key,
        @anim_speed_key,
        @anim_bright_min_key,
        @anim_bright_max_key,
        @anim_wave_step_key,
        @anim_opacity_key,
        @late_marker_key
      ])

    %{
      pattern: anim_enum(values, @anim_pattern_key, @anim_patterns, @default_pattern),
      mode: anim_enum(values, @anim_mode_key, @anim_modes, @default_mode),
      speed: anim_float(values, @anim_speed_key, @default_speed, @speed_range),
      brightness_min:
        anim_float(values, @anim_bright_min_key, @default_bright_min, @bright_min_range),
      brightness_max:
        anim_float(values, @anim_bright_max_key, @default_bright_max, @bright_max_range),
      wave_step: anim_float(values, @anim_wave_step_key, @default_wave_step, @wave_step_range),
      opacity: anim_float(values, @anim_opacity_key, @default_opacity, @opacity_range),
      late_marker: anim_enum(values, @late_marker_key, @late_markers, @default_late_marker)
    }
  end

  @doc """
  Persist one overdue-animation field (`"pattern"`, `"mode"`, `"speed"`,
  `"brightness_min"`, `"brightness_max"`, `"wave_step"`). An invalid field or
  value is ignored.
  """
  @spec put_animation(String.t(), term()) :: term()
  def put_animation("pattern", v) do
    if v in @anim_patterns,
      do: PhoenixKit.Settings.update_setting_with_module(@anim_pattern_key, v, @module),
      else: :ignore
  end

  def put_animation("mode", v) do
    if v in @anim_modes,
      do: PhoenixKit.Settings.update_setting_with_module(@anim_mode_key, v, @module),
      else: :ignore
  end

  def put_animation("speed", v), do: put_anim_float(@anim_speed_key, v, @speed_range)

  def put_animation("brightness_min", v),
    do: put_anim_float(@anim_bright_min_key, v, @bright_min_range)

  def put_animation("brightness_max", v),
    do: put_anim_float(@anim_bright_max_key, v, @bright_max_range)

  def put_animation("wave_step", v), do: put_anim_float(@anim_wave_step_key, v, @wave_step_range)
  def put_animation("opacity", v), do: put_anim_float(@anim_opacity_key, v, @opacity_range)

  def put_animation("late_marker", v) do
    if v in @late_markers,
      do: PhoenixKit.Settings.update_setting_with_module(@late_marker_key, v, @module),
      else: :ignore
  end

  def put_animation(_field, _value), do: :ignore

  @doc "Restore every overdue-animation setting to its default."
  @spec reset_animation() :: :ok
  def reset_animation do
    PhoenixKit.Settings.update_setting_with_module(@anim_pattern_key, @default_pattern, @module)
    PhoenixKit.Settings.update_setting_with_module(@anim_mode_key, @default_mode, @module)

    PhoenixKit.Settings.update_setting_with_module(
      @late_marker_key,
      @default_late_marker,
      @module
    )

    put_anim_float(@anim_speed_key, @default_speed, @speed_range)
    put_anim_float(@anim_bright_min_key, @default_bright_min, @bright_min_range)
    put_anim_float(@anim_bright_max_key, @default_bright_max, @bright_max_range)
    put_anim_float(@anim_wave_step_key, @default_wave_step, @wave_step_range)
    put_anim_float(@anim_opacity_key, @default_opacity, @opacity_range)
    :ok
  end

  @doc """
  The `<style>` block for the overdue animation, from an already-`read_animation/0`
  config map (callers thread the map so one read serves style + legend). Safe to
  inject with `Phoenix.HTML.raw/1`: every interpolated value is a validated enum
  or clamped number, never free text.
  """
  @spec animation_style(map()) :: String.t()
  def animation_style(cfg) do
    "<style>\n" <> animation_css(cfg) <> "\n" <> label_css() <> "\n</style>"
  end

  # Labels keep their per-bar black/white fill (palette text_color), but get a
  # thin OPPOSITE-colour halo so they stay legible over the overdue stripes (and
  # any bar colour): white text → dark halo, near-black text → light halo. The
  # bar carries the `text-white` / `text-neutral-900` class, so we can target
  # each case. Cheaper + more robust than per-letter colouring (no DOM split, no
  # broken truncation, survives the animation).
  defp label_css do
    """
    .cal-multiday-bar.text-white span { text-shadow: 0 0 2px rgba(0,0,0,0.9), 0 0 3px rgba(0,0,0,0.7); }
    .cal-multiday-bar.text-neutral-900 span { text-shadow: 0 0 2px rgba(255,255,255,0.95), 0 0 3px rgba(255,255,255,0.8); }\
    """
  end

  @doc """
  CSS body (no surrounding `<style>` tag) for an overdue-animation config map of
  the shape `read_animation/0` returns. Public so tests and a settings preview
  can render a given config without touching the settings store.
  """
  @spec animation_css(map()) :: String.t()
  def animation_css(cfg) do
    case Map.get(cfg, :pattern, @default_pattern) do
      "solid" -> solid_css(cfg)
      _ -> stripes_css(cfg)
    end
  end

  # ── Pattern: diagonal inverse-colour stripes (keeps the identity colour) ──

  # off → static stripes, no motion.
  defp stripes_css(%{mode: "off"} = cfg) do
    base_stripes(cfg) <>
      "\n@media (prefers-reduced-motion: reduce) { .pk-overdue::after { animation: none; } }"
  end

  # flash → the whole striped overlay pulses (opacity) in time. The brightness
  # pair scales around the configured stripe opacity (peak = opacity ×
  # brightness_max, capped at fully opaque).
  defp stripes_css(%{mode: "flash"} = cfg) do
    o = stripe_opacity(cfg)

    base_stripes(cfg) <>
      """

      @keyframes pk-overdue-stripe-flash {
        0%, 100% { opacity: #{num(opacity(o * cfg.brightness_min))}; }
        50% { opacity: #{num(opacity(o * cfg.brightness_max))}; }
      }
      .pk-overdue::after { animation: pk-overdue-stripe-flash #{num(cfg.speed)}s ease-in-out infinite; }
      @media (prefers-reduced-motion: reduce) { .pk-overdue::after { animation: none; } }\
      """
  end

  # wave → the stripes slide diagonally (a flowing barber-pole). 56.57px = one
  # 40px gradient period along x (40 / cos 45°), so the slide loops seamlessly.
  # Both endpoints carry the alignment offset (--pk-bg-x) so the slide stays
  # aligned across segments.
  defp stripes_css(cfg) do
    base_stripes(cfg) <>
      """

      @keyframes pk-overdue-stripe-slide {
        from { background-position: var(--pk-bg-x, 0) var(--pk-bg-y, 0); }
        to { background-position: calc(var(--pk-bg-x, 0) + 56.57px) var(--pk-bg-y, 0); }
      }
      .pk-overdue::after { animation: pk-overdue-stripe-slide #{num(cfg.speed)}s linear infinite; }
      @media (prefers-reduced-motion: reduce) { .pk-overdue::after { animation: none; } }\
      """
  end

  # ── Pattern: solid inverse-colour fill (the whole overdue stretch flips) ──

  # off → static inverse fill (mid brightness so it reads clearly, not glaring).
  defp solid_css(%{mode: "off"} = cfg) do
    ".pk-overdue { filter: invert(1) brightness(#{num((cfg.brightness_min + cfg.brightness_max) / 2)}); }"
  end

  # wave → each overdue day is phase-shifted by its absolute date (--pk-hl-day),
  # so one band travels across every project in sync. flash → same keyframe with
  # no delay, so all overdue days pulse together.
  defp solid_css(cfg) do
    delay =
      if cfg.mode == "wave",
        do: "\n      animation-delay: calc(var(--pk-hl-day, 0) * -#{num(cfg.wave_step)}s);",
        else: ""

    """
    @keyframes pk-overdue-wave {
          0%, 42%, 100% { filter: invert(1) brightness(#{num(cfg.brightness_min)}); }
          50% { filter: invert(1) brightness(#{num(cfg.brightness_max)}); }
          58% { filter: invert(1) brightness(#{num(cfg.brightness_min)}); }
        }
        .pk-overdue {
          filter: invert(1) brightness(#{num(cfg.brightness_min)});
          animation: pk-overdue-wave #{num(cfg.speed)}s ease-in-out infinite;#{delay}
        }
        @media (prefers-reduced-motion: reduce) {
          .pk-overdue { animation: none; filter: invert(1); }
        }\
    """
  end

  # The overdue stretch keeps its identity colour; a 45° repeating gradient of
  # white stripes blended with `difference` paints those stripes in the INVERSE
  # of the bar's own colour (white-difference = invert) while the gaps keep the
  # identity colour — so it reads as "hazard striped", not a solid recolour, and
  # you can still tell which project it is. To line the diagonals up across
  # day-cells and stacked rows WITHOUT pinning them to the viewport (which made
  # them glide on scroll), the `SyncAnimations` JS hook sets `--pk-bg-x/y` on each
  # segment to its offset from the calendar's origin, so every segment shows its
  # slice of ONE shared pattern that still scrolls with the bars. Label spans are
  # lifted above the overlay so they stay legible.
  defp base_stripes(cfg) do
    """
    .pk-overdue { position: relative; }
    .pk-overdue > span { position: relative; z-index: 1; }
    .pk-overdue::after {
      content: "";
      position: absolute;
      inset: 0;
      pointer-events: none;
      opacity: #{num(stripe_opacity(cfg))};
      background-image: repeating-linear-gradient(45deg, #fff 0 8px, transparent 8px 40px);
      background-position: var(--pk-bg-x, 0) var(--pk-bg-y, 0);
      background-size: 56.57px 56.57px;
      mix-blend-mode: difference;
    }\
    """
  end

  # The striped overlay's base opacity. Falls back to the default for maps
  # that predate the setting (tests, cached assigns from an older node).
  defp stripe_opacity(cfg), do: cfg |> Map.get(:opacity, @default_opacity) |> opacity()

  defp opacity(v), do: v |> max(0.0) |> min(1.0) |> Float.round(3)

  defp anim_enum(values, key, allowed, default) do
    value = Map.get(values, key, default)
    if value in allowed, do: value, else: default
  end

  defp anim_float(values, key, default, range) do
    case Float.parse(Map.get(values, key) || to_string(default)) do
      {f, _} -> clamp(f, range)
      :error -> default
    end
  end

  defp put_anim_float(key, value, range) do
    case Float.parse(to_string(value)) do
      {f, _} ->
        PhoenixKit.Settings.update_setting_with_module(key, to_string(clamp(f, range)), @module)

      :error ->
        :ignore
    end
  end

  defp clamp(f, {lo, hi}), do: f |> max(lo) |> min(hi)

  # Trim a float for CSS output: integers lose the trailing ".0" (7.0 -> "7").
  defp num(f) when is_float(f) do
    if f == Float.round(f), do: Integer.to_string(trunc(f)), else: Float.to_string(f)
  end
end
